services:
  mongo:
    image: mongo:latest
    container_name: grocery-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery-booking-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/grocery-booking
      - PORT=3000
    restart: always

volumes:
  mongo-data:
